### ISSUE TITLE
[PE-D][Tester B] (Very minor) Appointments could be sorted for better usability

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F09-4/tp#115]
Description: Currently, appointments are not sorted by date. This can make it hard to see which are the upcoming appointments.
Possible solution: Have an ObservableList that sorts the appointments by date-time every time a new appointment is added.

In this image, you can see how the appointments are not sorted by date/time.
![image.png](https://raw.githubusercontent.com/hiivan/ped/main/files/bb7e6f91-0dd8-4215-acd4-710b6a4bc54e.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: hiivan/ped#7

**Comment by joenus** [comment]
No plans to address feature flaws in 1.4
