### ISSUE TITLE
[PE-D][Tester C] Grammar issues

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F09-4/tp#123]
Minor grammar issue, should be patient's instead of patients'

![Screenshot 2024-04-05 at 5.49.41 PM.png](https://raw.githubusercontent.com/jiahui0309/ped/main/files/90022c41-55e9-4b8f-9ba9-2e2a54072a7c.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: jiahui0309/ped#9

**Comment by sebin0817** [comment]
Duplicated error raised by the same tester.
