### ISSUE TITLE
[PE-D][Tester E] Unable to execute edit-an command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F09-4/tp#99]
![Screenshot 2024-04-05 at 16.42.47.png](https://raw.githubusercontent.com/peienlim/ped/main/files/fbd86db2-b89f-4a6c-8136-0aa23c6f8763.png)

Previous command: `list` (hence the command box shows "listed all notes")
Command executed: `edit-an 1 d/10-10-2024`

The edit-an command does not execute even after pressing enter. It seems that there are some uncaught errors that prevent the command from executing, as seen in the screenshot of the terminal below.

![Screenshot 2024-04-05 at 16.45.50.png](https://raw.githubusercontent.com/peienlim/ped/main/files/29e79d9a-2f69-4f35-b22b-e4c812cc263e.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: peienlim/ped#5

**Comment by sebin0817** [comment]
Duplicated error, to be resolved in 1 issue.
